version: '3'

x-environment: &common-vars
    TZ: Europe/Rome

services:
  vsftpd:
    image: neomediatech/vsftpd-honey-alpine:latest
    hostname: vsftpd-honey
    ports:
      - '20:20'
      - '21:21'
    volumes:
      - /srv/data/docker/containers/honeypot/logs/:/data/logs/
    environment:
      << : *common-vars

